version: "3"

services:
  api:
    image: app
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    networks:
      - web
  postgres:
      image: postgres:latest
      container_name: postgres
      restart: always
      env_file:
        - .env
      volumes:
        - pgdata:/var/lib/postgresql/data
      ports:
        - ${POSTGRES_PORT}:${POSTGRES_PORT}
      networks:
        - web
      environment:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_DB=${POSTGRES_NAME}
      healthcheck:
        test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} ${POSTGRES_NAME}"]
        interval: 5s
        timeout: 5s
        retries: 5
volumes:
  api:
  pgdata:

networks:
  web:
    driver: bridge